from pathlib import Path

ROOT=Path('.')

def read(p): return (ROOT/p).read_text(encoding='utf-8')
def write(p,s): (ROOT/p).write_text(s,encoding='utf-8')
def once(s,a,b,label):
    if a not in s: raise RuntimeError(f'missing patch target: {label}')
    return s.replace(a,b,1)

def all_(s,a,b,label):
    if a not in s: raise RuntimeError(f'missing patch target: {label}')
    return s.replace(a,b)

schema=read('database/schema.sql')
schema=once(schema,"role TEXT NOT NULL CHECK(role IN ('MANAGER','INSPECTOR')), first_name","role TEXT NOT NULL CHECK(role IN ('MANAGER','INSPECTOR')), position TEXT NOT NULL DEFAULT 'UNSPECIFIED', first_name",'sqlite position')
schema=once(schema,'CREATE INDEX IF NOT EXISTS idx_users_org ON users(organization_id);',"CREATE INDEX IF NOT EXISTS idx_users_org ON users(organization_id);\nCREATE INDEX IF NOT EXISTS idx_users_position ON users(position);",'sqlite index')
write('database/schema.sql',schema)

pg=read('database/postgresql-schema.sql')
pg=once(pg,"role TEXT NOT NULL CHECK(role IN ('MANAGER','INSPECTOR')), first_name","role TEXT NOT NULL CHECK(role IN ('MANAGER','INSPECTOR')), position TEXT NOT NULL DEFAULT 'UNSPECIFIED', first_name",'postgres position')
pg=once(pg,'CREATE INDEX IF NOT EXISTS idx_users_org ON users(organization_id);',"CREATE INDEX IF NOT EXISTS idx_users_org ON users(organization_id);\nCREATE INDEX IF NOT EXISTS idx_users_position ON users(position);",'postgres index')
write('database/postgresql-schema.sql',pg)

s=read('api/server.mjs')
s=once(s,"const schema = await readFile(join(ROOT,'database/schema.sql'),'utf8'); db.exec(schema);",'''const schema = await readFile(join(ROOT,'database/schema.sql'),'utf8'); db.exec(schema);
function ensureUserPosition(){const cols=db.prepare('PRAGMA table_info(users)').all();if(!cols.some(c=>c.name==='position'))db.exec("ALTER TABLE users ADD COLUMN position TEXT NOT NULL DEFAULT 'UNSPECIFIED'");db.exec("UPDATE users SET position=CASE WHEN role='MANAGER' THEN 'UNION_PRESIDENT' WHEN role='INSPECTOR' THEN 'UNION_INSPECTOR' ELSE position END WHERE position='UNSPECIFIED'")}
ensureUserPosition();''','server migration')
s=all_(s,'INSERT INTO users VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',"INSERT INTO users(id,organization_id,role,position,first_name,last_name,personnel_code,mobile,username,password_hash,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",'user insert shape')
s=once(s,"`).run(mgr,orgId,'MANAGER','مدیر'","`).run(mgr,orgId,'MANAGER','UNION_PRESIDENT','مدیر'",'manager seed')
s=once(s,"`).run(ins,orgId,'INSPECTOR','بازرس'","`).run(ins,orgId,'INSPECTOR','UNION_INSPECTOR','بازرس'",'inspector seed')
s=once(s,"function publicUser(u){ return {id:u.id,organizationId:u.organization_id,role:u.role,firstName:u.first_name,lastName:u.last_name,personnelCode:u.personnel_code,mobile:u.mobile,username:u.username,status:u.status}; }",'''function publicUser(u){const org=db.prepare('SELECT name FROM organizations WHERE id=?').get(u.organization_id);return {id:u.id,organizationId:u.organization_id,organizationName:org?.name||'',role:u.role,position:u.position||'UNSPECIFIED',firstName:u.first_name,lastName:u.last_name,personnelCode:u.personnel_code,mobile:u.mobile,username:u.username,status:u.status}}
function positionLabel(p){return ({UNION_PRESIDENT:'رئیس اتحادیه',UNION_INSPECTOR:'بازرس اتحادیه',CHAMBER_PRESIDENT:'رئیس اتاق اصناف',CHAMBER_INSPECTOR:'بازرس اتاق اصناف',INSPECTION_RESPONSIBLE:'مسئول بازرسی'})[p]||p||'نامشخص'}
function canSupervise(u){return u.role==='MANAGER'}
function scopeOrganizationIds(u){if(u.position==='CHAMBER_PRESIDENT')return db.prepare('SELECT id FROM organizations').all().map(x=>x.id);return [u.organization_id]}''','authorization helpers')
old="const role=b.role==='MANAGER'?'MANAGER':'INSPECTOR'; if(role==='MANAGER' && b.inviteCode!=='PAKDASHT-DEMO-MGR') return send(res,403,{error:'MANAGER_INVITE_REQUIRED'}); const organizationName=String(b.organizationName).replace(/\\u00a0/g,' ').replace(/\\s+/g,' ').trim();"
new="const role=b.role==='MANAGER'?'MANAGER':'INSPECTOR'; const position=String(b.position||'').trim(); const organizationName=String(b.organizationName).replace(/\\u00a0/g,' ').replace(/\\s+/g,' ').trim(); const chamber=normalizeOrganizationName(organizationName)==='اتاق اصناف'; const allowedPositions=chamber?['CHAMBER_PRESIDENT','CHAMBER_INSPECTOR','INSPECTION_RESPONSIBLE']:['UNION_PRESIDENT','UNION_INSPECTOR']; if(!allowedPositions.includes(position))return send(res,400,{error:'INVALID_ROLE'}); if((position==='CHAMBER_INSPECTOR'||position==='UNION_INSPECTOR')&&role!=='INSPECTOR')return send(res,400,{error:'INVALID_ROLE'}); if((position==='CHAMBER_PRESIDENT'||position==='INSPECTION_RESPONSIBLE'||position==='UNION_PRESIDENT')&&b.presidentCode!=='aaa123')return send(res,403,{error:'PRESIDENT_CODE_REQUIRED'});"
s=once(s,old,new,'registration flow')
s=once(s,"`).run(id,orgId,role,b.firstName,b.lastName,b.personnelCode||'',b.mobile,b.username,hashPassword(b.password),'ACTIVE',now(),now());","`).run(id,orgId,role,position,b.firstName,b.lastName,b.personnelCode||'',b.mobile,b.username,hashPassword(b.password),'ACTIVE',now(),now());",'registration insert')
s=once(s,"if(method==='POST' && u.role==='INSPECTOR'){ const b=await json(req); if(!b.name||!Number.isFinite(Number(b.latitude))||!Number.isFinite(Number(b.longitude)))return send(res,400,{error:'INVALID_SHOP'});","if(method==='POST' && u.role==='INSPECTOR'){ const b=await json(req); if(!b.name||!Number.isFinite(Number(b.latitude))||!Number.isFinite(Number(b.longitude))||!['HAS_LICENSE','NO_LICENSE'].includes(b.businessLicense))return send(res,400,{error:'INVALID_SHOP'});",'license validation')
s=once(s,"if(method==='GET'){ const rows=db.prepare('SELECT * FROM shops WHERE organization_id=? ORDER BY created_at DESC').all(u.organization_id); return send(res,200,{items:rows}); }","if(method==='GET'){const ids=scopeOrganizationIds(u);const marks=ids.map(()=>'?').join(',');const rows=db.prepare(`SELECT * FROM shops WHERE organization_id IN (${marks}) ORDER BY created_at DESC`).all(...ids);return send(res,200,{items:rows});}",'shop scope')
s=once(s,"if(parts[1]==='employees' && method==='GET' && u.role==='MANAGER'){ const rows=db.prepare(`SELECT id,first_name,last_name,personnel_code,mobile,username,status,role FROM users WHERE organization_id=? AND role='INSPECTOR'`).all(u.organization_id); return send(res,200,{items:rows.map(x=>({id:x.id,firstName:x.first_name,lastName:x.last_name,personnelCode:x.personnel_code,mobile:x.mobile,username:x.username,status:x.status,role:x.role}))}); }",'''if(parts[1]==='employees' && method==='GET' && canSupervise(u)){let rows=[];if(u.position==='CHAMBER_PRESIDENT'){rows=db.prepare(`SELECT u.id,u.first_name,u.last_name,u.personnel_code,u.mobile,u.username,u.status,u.role,u.position,o.name organization_name FROM users u JOIN organizations o ON o.id=u.organization_id WHERE u.position IN ('UNION_PRESIDENT','UNION_INSPECTOR','CHAMBER_INSPECTOR') ORDER BY o.name,u.last_name,u.first_name`).all()}else if(u.position==='INSPECTION_RESPONSIBLE'){rows=db.prepare(`SELECT u.id,u.first_name,u.last_name,u.personnel_code,u.mobile,u.username,u.status,u.role,u.position,o.name organization_name FROM users u JOIN organizations o ON o.id=u.organization_id WHERE u.organization_id=? AND u.position='CHAMBER_INSPECTOR' ORDER BY u.last_name,u.first_name`).all(u.organization_id)}else{rows=db.prepare(`SELECT u.id,u.first_name,u.last_name,u.personnel_code,u.mobile,u.username,u.status,u.role,u.position,o.name organization_name FROM users u JOIN organizations o ON o.id=u.organization_id WHERE u.organization_id=? AND u.position='UNION_INSPECTOR' ORDER BY u.last_name,u.first_name`).all(u.organization_id)}return send(res,200,{items:rows.map(x=>({id:x.id,firstName:x.first_name,lastName:x.last_name,personnelCode:x.personnel_code,mobile:x.mobile,username:x.username,status:x.status,role:x.role,position:x.position,roleLabel:positionLabel(x.position),organizationName:x.organization_name}))})}''','employee scope')
s=once(s,"if(method==='GET'){ let rows=db.prepare('SELECT * FROM missions WHERE organization_id=? ORDER BY created_at DESC').all(u.organization_id); if(u.role==='INSPECTOR') rows=rows.filter(x=>x.inspector_id===u.id); return send(res,200,{items:rows}); }","if(method==='GET'){const ids=scopeOrganizationIds(u);const marks=ids.map(()=>'?').join(',');let rows=db.prepare(`SELECT * FROM missions WHERE organization_id IN (${marks}) ORDER BY created_at DESC`).all(...ids);if(u.role==='INSPECTOR')rows=rows.filter(x=>x.inspector_id===u.id);return send(res,200,{items:rows});}",'mission scope')
s=once(s,"if(parts[1]==='route' && method==='GET' && parts[2]){ const m=db.prepare('SELECT * FROM missions WHERE id=? AND organization_id=?').get(parts[2],u.organization_id); if(!m || (u.role==='INSPECTOR'&&m.inspector_id!==u.id))return send(res,404,{error:'NOT_FOUND'});","if(parts[1]==='route' && method==='GET' && parts[2]){const ids=scopeOrganizationIds(u);const marks=ids.map(()=>'?').join(',');const m=db.prepare(`SELECT * FROM missions WHERE id=? AND organization_id IN (${marks})`).get(parts[2],...ids);if(!m||(u.role==='INSPECTOR'&&m.inspector_id!==u.id))return send(res,404,{error:'NOT_FOUND'});",'route scope')
oldmon="if(parts[1]==='monitoring' && method==='GET' && u.role==='MANAGER'){ const rows=db.prepare(`SELECT m.*,u.first_name,u.last_name FROM missions m JOIN users u ON u.id=m.inspector_id WHERE m.organization_id=? AND m.status='ACTIVE'`).all(u.organization_id); return send(res,200,{items:rows}); }"
newmon="""if(parts[1]==='monitoring' && method==='GET' && canSupervise(u)){const ids=scopeOrganizationIds(u);const marks=ids.map(()=>'?').join(',');let filter='';if(u.position==='INSPECTION_RESPONSIBLE')filter=\" AND u.position='CHAMBER_INSPECTOR'\";else if(u.position==='UNION_PRESIDENT')filter=\" AND u.position='UNION_INSPECTOR'\";else if(u.position==='CHAMBER_PRESIDENT')filter=\" AND u.position IN ('UNION_INSPECTOR','CHAMBER_INSPECTOR')\";const rows=db.prepare(`SELECT m.*,u.first_name,u.last_name,u.position,o.name organization_name FROM missions m JOIN users u ON u.id=m.inspector_id JOIN organizations o ON o.id=u.organization_id WHERE m.organization_id IN (${marks}) AND m.status='ACTIVE'${filter}`).all(...ids);const shops=db.prepare(`SELECT * FROM shops WHERE organization_id IN (${marks}) ORDER BY created_at DESC`).all(...ids);return send(res,200,{items:rows.map(x=>({...x,roleLabel:positionLabel(x.position)})),shops})}"""
s=once(s,oldmon,newmon,'monitoring')
marker=" if(parts[1]==='monitoring' && method==='GET' && canSupervise(u))"
lists=""" if(parts[1]==='inspections' && method==='GET'){const ids=scopeOrganizationIds(u);const marks=ids.map(()=>'?').join(',');const rows=db.prepare(`SELECT i.*,s.name shop_name,u.first_name inspector_first_name,u.last_name inspector_last_name FROM inspections i JOIN shops s ON s.id=i.shop_id JOIN users u ON u.id=i.inspector_id WHERE i.organization_id IN (${marks}) ORDER BY i.timestamp DESC`).all(...ids);if(u.role==='INSPECTOR')return send(res,200,{items:rows.filter(x=>x.inspector_id===u.id)});if(!canSupervise(u))return send(res,403,{error:'FORBIDDEN'});return send(res,200,{items:rows})}
 if(parts[1]==='warnings' && method==='GET'){const ids=scopeOrganizationIds(u);const marks=ids.map(()=>'?').join(',');const rows=db.prepare(`SELECT w.*,s.name shop_name,u.first_name inspector_first_name,u.last_name inspector_last_name FROM warnings w JOIN shops s ON s.id=w.shop_id JOIN users u ON u.id=w.inspector_id WHERE w.organization_id IN (${marks}) ORDER BY w.date DESC`).all(...ids);if(u.role==='INSPECTOR')return send(res,200,{items:rows.filter(x=>x.inspector_id===u.id)});if(!canSupervise(u))return send(res,403,{error:'FORBIDDEN'});return send(res,200,{items:rows})}
"""+marker
s=once(s,marker,lists,'inspection warning GET')
s=once(s,"if(parts[1]==='reports' && method==='GET' && u.role==='MANAGER'){ const shops=db.prepare('SELECT * FROM shops WHERE organization_id=?').all(u.organization_id); const inspections=db.prepare('SELECT * FROM inspections WHERE organization_id=?').all(u.organization_id); const warnings=db.prepare('SELECT * FROM warnings WHERE organization_id=?').all(u.organization_id); const missions=db.prepare('SELECT * FROM missions WHERE organization_id=?').all(u.organization_id); return send(res,200,{shops,inspections,warnings,missions}); }","if(parts[1]==='reports' && method==='GET' && canSupervise(u)){const ids=scopeOrganizationIds(u);const marks=ids.map(()=>'?').join(',');const shops=db.prepare(`SELECT * FROM shops WHERE organization_id IN (${marks})`).all(...ids);const inspections=db.prepare(`SELECT * FROM inspections WHERE organization_id IN (${marks})`).all(...ids);const warnings=db.prepare(`SELECT * FROM warnings WHERE organization_id IN (${marks})`).all(...ids);const missions=db.prepare(`SELECT * FROM missions WHERE organization_id IN (${marks})`).all(...ids);return send(res,200,{shops,inspections,warnings,missions});}",'report scope')
write('api/server.mjs',s)

app=read('web/app.js')
oldui='''<div class="login-page"><div class="login-card"><h1>ایجاد حساب</h1><p class="muted">برای Manager نیاز به کد دعوت معتبر سازمان دارید.</p><div class="form-grid"><div class="field"><label>نام</label><input id="f1"></div><div class="field"><label>نام خانوادگی</label><input id="f2"></div><div class="field"><label>کد پرسنلی</label><input id="f3"></div><div class="field"><label>موبایل</label><input id="f4" inputmode="tel"></div><div class="field"><label>نام کاربری</label><input id="f5"></div><div class="field"><label>رمز عبور</label><input id="f6" type="password"></div><div class="field"><label>نام سازمان/اتحادیه</label><input id="f7" value="اتحادیه نمونه پاکدشت"></div><div class="field"><label>نقش</label><select id="f8"><option value="INSPECTOR">بازرس</option><option value="MANAGER">مدیر</option></select></div></div><div class="field" style="margin-top:10px"><label>کد دعوت مدیر (فقط برای Manager)</label><input id="f9" placeholder="در حالت Demo: PAKDASHT-DEMO-MGR"></div><div id="regErr" class="alert hidden" style="margin-top:10px"></div><div class="row" style="margin-top:14px"><button class="btn primary" id="reg">ساخت حساب</button><button class="btn ghost" id="back">بازگشت</button></div></div></div>'''
newui='''<div class="login-page"><div class="login-card"><h1>ایجاد حساب</h1><p class="muted">نوع سازمان و نقش خود را انتخاب کنید.</p><div class="form-grid"><div class="field"><label>نام</label><input id="f1"></div><div class="field"><label>نام خانوادگی</label><input id="f2"></div><div class="field"><label>کد پرسنلی</label><input id="f3"></div><div class="field"><label>موبایل</label><input id="f4" inputmode="tel"></div><div class="field"><label>نام کاربری</label><input id="f5"></div><div class="field"><label>رمز عبور</label><input id="f6" type="password"></div><div class="field"><label>سازمان</label><select id="f7"><option value="اتحادیه نمونه پاکدشت">اتحادیه نمونه پاکدشت</option><option value="اتاق اصناف">اتاق اصناف</option></select></div><div class="field"><label>نقش</label><select id="f8"></select></div></div><div id="presidentCodeWrap" class="field hidden" style="margin-top:10px"><label>کد ورود رئیس</label><input id="f9" type="password" autocomplete="off"></div><div id="regErr" class="alert hidden" style="margin-top:10px"></div><div class="row" style="margin-top:14px"><button class="btn primary" id="reg">ساخت حساب</button><button class="btn ghost" id="back">بازگشت</button></div></div></div>'''
app=once(app,oldui,newui,'registration UI')
oldtail="""$('#back').onclick=login;$('#reg').onclick=async()=>{try{await api('auth/register',{method:'POST',body:JSON.stringify({firstName:$('#f1').value,lastName:$('#f2').value,personnelCode:$('#f3').value,mobile:$('#f4').value,username:$('#f5').value,password:$('#f6').value,organizationName:$('#f7').value,role:$('#f8').value,inviteCode:$('#f9').value})});toast('حساب ساخته شد؛ اکنون وارد شوید');setTimeout(login,700)}catch(e){$('#regErr').textContent=e.message;$('#regErr').classList.remove('hidden')}}}"""
newtail="""$('#back').onclick=login;const roleOptions=()=>{const chamber=$('#f7').value==='اتاق اصناف';$('#f8').innerHTML=chamber?'<option value=\"CHAMBER_PRESIDENT\">رئیس اتاق اصناف</option><option value=\"CHAMBER_INSPECTOR\">بازرس اتاق اصناف</option><option value=\"INSPECTION_RESPONSIBLE\">مسئول بازرسی</option>':'<option value=\"UNION_PRESIDENT\">رئیس اتحادیه</option><option value=\"UNION_INSPECTOR\">بازرس اتحادیه</option>';const p=['CHAMBER_PRESIDENT','INSPECTION_RESPONSIBLE','UNION_PRESIDENT'].includes($('#f8').value);$('#presidentCodeWrap').classList.toggle('hidden',!p)};$('#f7').onchange=roleOptions;$('#f8').onchange=roleOptions;roleOptions();$('#reg').onclick=async()=>{try{const position=$('#f8').value;const role=position.endsWith('INSPECTOR')?'INSPECTOR':'MANAGER';await api('auth/register',{method:'POST',body:JSON.stringify({firstName:$('#f1').value,lastName:$('#f2').value,personnelCode:$('#f3').value,mobile:$('#f4').value,username:$('#f5').value,password:$('#f6').value,organizationName:$('#f7').value,role,position,presidentCode:$('#f9').value})});toast('حساب ساخته شد؛ اکنون وارد شوید');setTimeout(login,700)}catch(e){$('#regErr').textContent=e.message;$('#regErr').classList.remove('hidden')}}}"""
app=once(app,oldtail,newtail,'registration submit')
app=once(app,"function navItems(){return state.user.role==='INSPECTOR'?[['dashboard','🏠','داشبورد'],['map','🗺️','نقشه'],['missions','🚀','مأموریت‌ها'],['shops','🏪','واحدها'],['inspections','📋','بازرسی‌ها'],['warnings','⚠️','اخطارها'],['profile','👤','پروفایل']]:[['dashboard','📊','داشبورد'],['monitoring','📡','نظارت زنده'],['employees','👥','کارمندان'],['map','🗺️','نقشه'],['shops','🏪','واحدها'],['missions','🚀','مأموریت‌ها'],['routes','🧭','مسیرها'],['reports','📈','گزارش‌ها'],['profile','👤','پروفایل']];}","function navItems(){return state.user.role==='INSPECTOR'?[['dashboard','🏠','داشبورد'],['map','🗺️','نقشه'],['missions','🚀','مأموریت‌ها'],['shops','🏪','واحدها'],['inspections','📋','بازرسی‌ها'],['warnings','⚠️','اخطارها'],['profile','👤','پروفایل']]:[['dashboard','📊','داشبورد'],['monitoring','📡','نظارت زنده'],['employees','👥','افراد تحت نظارت'],['map','🗺️','نقشه'],['shops','🏪','واحدها'],['missions','🚀','مأموریت‌ها'],['routes','🧭','مسیرها'],['reports','📈','گزارش‌ها'],['profile','👤','پروفایل']];}",'nav')
app=once(app,'<div class="field"><label>شماره پروانه</label><input id="s5"></div>','<div class="field"><label>پروانه کسب</label><select id="s5"><option value="HAS_LICENSE">دارد</option><option value="NO_LICENSE">ندارد</option></select></div>','license UI')
oldgeneric="""function genericList(c,title,type){c.innerHTML=`<div class="page-head"><div><h1>${title}</h1><div class="muted">داده‌های این بخش از API سازمانی خوانده می‌شوند.</div></div></div><div class="card"><div class="empty">برای مشاهده کامل ${title} در این نسخه، گزارش سازمانی و API آماده است. ثبت داده از جریان اصلی مأموریت انجام می‌شود.</div></div>`}"""
newgeneric="""async function genericList(c,title,type){let d;try{d=await api(type)}catch(e){return toast(e.message)}const rows=d.items||[];c.innerHTML=`<div class="page-head"><div><h1>${title}</h1><div class="muted">${rows.length} رکورد ذخیره‌شده در محدوده دسترسی شما.</div></div></div><div class="card table-wrap"><table class="table"><thead><tr>${type==='inspections'?'<th>واحد</th><th>بازرس</th><th>نتیجه</th><th>توضیحات</th><th>زمان</th>':'<th>شماره اخطار</th><th>واحد</th><th>بازرس</th><th>علت</th><th>توضیحات</th><th>زمان</th>'}</tr></thead><tbody>${rows.map(x=>type==='inspections'?`<tr><td>${esc(x.shop_name)}</td><td>${esc((x.inspector_first_name||'')+' '+(x.inspector_last_name||''))}</td><td>${esc(x.result)}</td><td>${esc(x.notes||'-')}</td><td>${new Date(x.timestamp).toLocaleString('fa-IR')}</td></tr>`:`<tr><td>${esc(x.warning_number)}</td><td>${esc(x.shop_name)}</td><td>${esc((x.inspector_first_name||'')+' '+(x.inspector_last_name||''))}</td><td>${esc(x.reason)}</td><td>${esc(x.description||'-')}</td><td>${new Date(x.date).toLocaleString('fa-IR')}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">رکوردی وجود ندارد.</td></tr>'}</tbody></table></div>`}"""
app=once(app,oldgeneric,newgeneric,'inspection warning lists')
app=once(app,"if(state.user.role==='MANAGER'){state.employees=(await api('employees')).items;state.monitoring=(await api('monitoring')).items}","if(state.user.role==='MANAGER'){state.employees=(await api('employees')).items;const mon=await api('monitoring');state.monitoring=mon.items;state.monitoringShops=mon.shops||[]}",'monitoring load')
oldmon="""function monitoring(c){c.innerHTML=`<div class="page-head"><div><h1>نظارت زنده</h1><div class="muted">موقعیت لحظه‌ای بازرسان فعال از کانال Realtime دریافت می‌شود.</div></div></div><div class="grid two"><div class="card"><h3>بازرسان فعال</h3>${state.monitoring.map(m=>`<div class="row" style="justify-content:space-between;padding:12px 0;border-bottom:1px solid var(--line)"><div><b>${m.first_name} ${m.last_name}</b><div class="muted">Mission ${esc(m.id.slice(0,8))}…</div></div><span class="pill ok">فعال</span></div>`).join('')||'<div class="empty">در حال حاضر مأموریت فعالی ثبت نشده است.</div>'}</div><div class="card"><h3>Realtime</h3><p class="muted">این پنل برای اتصال به WebSocket/SSE طراحی شده است. سرور فعلی SSE را در اختیار Frontend قرار می‌دهد.</p><div class="pill ok">SSE Ready</div></div></div>`}"""
newmon="""function monitoring(c){c.innerHTML=`<div class="page-head"><div><h1>نظارت زنده</h1><div class="muted">نقشه یکپارچه بازرسان و واحدهای صنفی در محدوده مجاز شما.</div></div></div><div class="card" style="padding:8px"><div class="map" id="supervisionMap"><div class="map-canvas" id="supervisionMapCanvas"></div><div class="map-controls"><button id="supZin">＋</button><button id="supZout">−</button></div></div></div><div class="card" style="margin-top:14px"><h3>بازرسان تحت نظارت</h3>${state.monitoring.map(m=>`<div class="row" style="justify-content:space-between;padding:10px 0;border-bottom:1px solid var(--line)"><div><b>${esc(m.first_name+' '+m.last_name)}</b><div class="muted">${esc(m.roleLabel||'بازرس')} · ${esc(m.organization_name||'')}</div></div><span class="pill ok">فعال</span></div>`).join('')||'<div class="empty">بازرس فعالی وجود ندارد.</div>'}</div>`;initSupervisionMap();$('#supZin').onclick=()=>{state.supervisionZoom=Math.min(18,(state.supervisionZoom||13)+1);drawSupervisionMap()};$('#supZout').onclick=()=>{state.supervisionZoom=Math.max(10,(state.supervisionZoom||13)-1);drawSupervisionMap()}}
function initSupervisionMap(){state.supervisionZoom=state.supervisionZoom||13;state.supervisionCenter=state.supervisionCenter||{lat:35.474,lng:51.685};drawSupervisionMap()}
function drawSupervisionMap(){const el=$('#supervisionMap'),canvas=$('#supervisionMapCanvas');if(!el||!canvas)return;canvas.innerHTML='';const z=state.supervisionZoom||13,c=geoXY(state.supervisionCenter.lat,state.supervisionCenter.lng,z),w=el.clientWidth,h=el.clientHeight;const add=(lat,lng,cls,label,emoji)=>{const p=geoXY(lat,lng,z),x=(p.x-c.x)*256+w/2,y=(p.y-c.y)*256+h/2;if(x<-50||x>w+50||y<-50||y>h+50)return;const d=document.createElement('button');d.className='marker '+cls;d.style.left=x+'px';d.style.top=y+'px';d.title=label;d.innerHTML=`<span>${emoji}</span>`;canvas.appendChild(d)};const tx=Math.floor(c.x),ty=Math.floor(c.y);for(let ix=tx-2;ix<=tx+2;ix++)for(let iy=ty-2;iy<=ty+2;iy++){const im=document.createElement('img');im.className='tile';im.src=`https://tile.openstreetmap.org/${z}/${ix}/${iy}.png`;im.style.left=(ix-c.x)*256+w/2+'px';im.style.top=(iy-c.y)*256+h/2+'px';canvas.appendChild(im)};state.monitoring.forEach(m=>{if(Number.isFinite(Number(m.start_latitude))&&Number.isFinite(Number(m.start_longitude)))add(Number(m.start_latitude),Number(m.start_longitude),'me',m.first_name+' '+m.last_name,'🧑‍💼')});(state.monitoringShops||[]).forEach(s=>add(Number(s.latitude),Number(s.longitude),'shop',s.name,'🏪'))}"""
app=once(app,oldmon,newmon,'unified map')
oldemp="""function employees(c){c.innerHTML=`<div class="page-head"><div><h1>کارمندان</h1></div></div><div class="card table-wrap"><table class="table"><thead><tr><th>نام</th><th>کد پرسنلی</th><th>موبایل</th><th>وضعیت</th></tr></thead><tbody>${state.employees.map(e=>`<tr><td>${e.firstName} ${e.lastName}</td><td>${e.personnelCode||'-'}</td><td>${e.mobile||'-'}</td><td><span class="pill ${e.status==='ACTIVE'?'ok':''}">${e.status}</span></td></tr>`).join('')}</tbody></table></div>`}"""
newemp="""function employees(c){c.innerHTML=`<div class="page-head"><div><h1>افراد تحت نظارت</h1><div class="muted">نقش و سازمان هر فرد مستقیماً از Backend خوانده می‌شود.</div></div></div><div class="card table-wrap"><table class="table"><thead><tr><th>نام</th><th>نقش</th><th>اتحادیه/سازمان</th><th>کد پرسنلی</th><th>وضعیت</th></tr></thead><tbody>${state.employees.map(e=>`<tr><td>${esc(e.firstName+' '+e.lastName)}</td><td>${esc(e.roleLabel||e.position||e.role)}</td><td>${esc(e.organizationName||'-')}</td><td>${esc(e.personnelCode||'-')}</td><td><span class="pill ${e.status==='ACTIVE'?'ok':''}">${esc(e.status)}</span></td></tr>`).join('')||'<tr><td colspan="5" class="empty">موردی وجود ندارد.</td></tr>'}</tbody></table></div>`}"""
app=once(app,oldemp,newemp,'employee identity')
write('web/app.js',app)
print('PATCH_OK')
