import { createServer } from 'node:http';
import { readFile, mkdir, stat } from 'node:fs/promises';
import { createHash, randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import { join, dirname, extname, resolve, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { config } from './config.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const PORT = config.port;
const DB_FILE = config.dbFile;
const WEB = join(ROOT,'web');
const now = () => new Date().toISOString();
const uid = () => crypto.randomUUID();
await mkdir(dirname(DB_FILE), {recursive:true});
const db = new DatabaseSync(DB_FILE);
db.exec(`PRAGMA foreign_keys = ON; PRAGMA journal_mode = WAL;`);
const schema = await readFile(join(ROOT,'database/schema.sql'),'utf8'); db.exec(schema);
function ensureUserPosition(){const cols=db.prepare('PRAGMA table_info(users)').all();if(!cols.some(c=>c.name==='position'))db.exec("ALTER TABLE users ADD COLUMN position TEXT NOT NULL DEFAULT 'UNSPECIFIED'");db.exec("UPDATE users SET position=CASE WHEN role='MANAGER' THEN 'UNION_PRESIDENT' WHEN role='INSPECTOR' THEN 'UNION_INSPECTOR' ELSE position END WHERE position='UNSPECIFIED'")}
ensureUserPosition();

function hashPassword(password){ const salt=randomBytes(16).toString('hex'); const key=scryptSync(password,salt,64).toString('hex'); return `scrypt$${salt}$${key}`; }
function verifyPassword(password, stored){ const [,salt,key]=stored.split('$'); const candidate=scryptSync(password,salt,64); return timingSafeEqual(candidate,Buffer.from(key,'hex')); }
function hashToken(token){ return createHash('sha256').update(token).digest('hex'); }
function send(res,status,data,headers={}){ const body=typeof data==='string'?data:JSON.stringify(data); res.writeHead(status,{'Content-Type':typeof data==='string'?'text/plain; charset=utf-8':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'no-referrer',...headers}); res.end(body); }
async function json(req){ let s=''; for await(const c of req){ s+=c; if(Buffer.byteLength(s)>config.maxBodyBytes) throw Object.assign(new Error('PAYLOAD_TOO_LARGE'),{statusCode:413}); } try{return s?JSON.parse(s):{};}catch{throw Object.assign(new Error('INVALID_JSON'),{statusCode:400});} }
const buckets=new Map();
function clientIp(req){ return config.trustProxy ? String(req.headers['x-forwarded-for']||'').split(',')[0].trim() || req.socket.remoteAddress || 'unknown' : req.socket.remoteAddress || 'unknown'; }
function rateLimit(req,res,limit){ const key=`${clientIp(req)}:${req.url?.startsWith('/api/auth/')?'auth':'api'}`; const nowMs=Date.now(); let b=buckets.get(key); if(!b || nowMs-b.started>=config.rateLimitWindowMs) b={started:nowMs,count:0}; b.count++; buckets.set(key,b); if(b.count>limit){ const retry=Math.ceil((config.rateLimitWindowMs-(nowMs-b.started))/1000); send(res,429,{error:'RATE_LIMITED',retryAfterSeconds:retry},{'Retry-After':String(retry)}); return false;} return true; }
function pathParts(url){ return new URL(url,'http://localhost').pathname.split('/').filter(Boolean); }
function auth(req){ const h=req.headers.authorization||''; const cookie=String(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('session_token=')); const token=h.startsWith('Bearer ')?h.slice(7):(cookie?decodeURIComponent(cookie.slice('session_token='.length)):''); if(!token)return null; const row=db.prepare(`SELECT s.*,u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?`).get(hashToken(token),now()); return row||null; }
function requireRole(req,res,role){ const u=auth(req); if(!u){send(res,401,{error:'UNAUTHORIZED'});return null;} if(u.status!=='ACTIVE'||(role&&u.role!==role)){send(res,403,{error:'FORBIDDEN'});return null;} return u; }
function audit(u,action,entity='',entityId='',metadata={}){ db.prepare(`INSERT INTO audit_logs VALUES(?,?,?,?,?,?,?,?)`).run(uid(),u.organization_id,u.id,action,entity,entityId,now(),JSON.stringify(metadata)); }
function seed(){
 if(!config.demoMode) return;
 const demoManagerPassword=process.env.DEMO_MANAGER_PASSWORD, demoInspectorPassword=process.env.DEMO_INSPECTOR_PASSWORD;
 if(!demoManagerPassword||!demoInspectorPassword){console.warn('DEMO_MODE is enabled but demo passwords are not configured; demo seed skipped.');return;}
 const orgId='org-pakdasht-demo'; const existing=db.prepare('SELECT id FROM organizations WHERE id=?').get(orgId); if(existing) return;
 db.prepare('INSERT INTO organizations VALUES(?,?,?,?)').run(orgId,'اتحادیه نمونه پاکدشت','Asia/Tehran',now());
 const mgr=uid(), ins=uid(); db.prepare(`INSERT INTO users(id,organization_id,role,position,first_name,last_name,personnel_code,mobile,username,password_hash,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(mgr,orgId,'MANAGER','UNION_PRESIDENT','مدیر','نمونه','MGR-001','09120000001','manager.demo',hashPassword(demoManagerPassword), 'ACTIVE',now(),now()); db.prepare(`INSERT INTO users(id,organization_id,role,position,first_name,last_name,personnel_code,mobile,username,password_hash,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(ins,orgId,'INSPECTOR','UNION_INSPECTOR','بازرس','نمونه','INS-001','09120000002','inspector.demo',hashPassword(demoInspectorPassword),'ACTIVE',now(),now());
 const base=[['فروشگاه نمونه بهار','علی نمونه','فروش پوشاک','خیابان امام خمینی پاکدشت',35.4740,51.6850],['واحد صنفی نمونه مهر','رضا نمونه','کیف و کفش','بلوار شهدای پاکدشت',35.4705,51.6785],['سوپرمارکت نمونه','مریم نمونه','خواربار','بلوار سپاه پاکدشت',35.4680,51.6920],['لوازم خانگی نمونه','سارا نمونه','لوازم خانگی','خیابان مطهری پاکدشت',35.4810,51.6810],['پوشاک نمونه غرب','محمد نمونه','پوشاک','میدان امام پاکدشت',35.4650,51.6740]];
 for(const [name,owner,cat,address,lat,lng] of base){ const id=uid(); db.prepare(`INSERT INTO shops VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,orgId,name,owner,'09120000000','0000000000','DEMO-000',cat,address,lat,lng,10,now(),'داده آزمایشی',ins,now(),now(),1); }
 const mission=uid(); const t1=new Date(Date.now()-3600e3).toISOString(),t2=new Date(Date.now()-1800e3).toISOString(); db.prepare(`INSERT INTO missions VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(mission,orgId,ins,'COMPLETED',t1,t2,35.4700,51.6800,35.4750,51.6850,1200,now(),now(),1);
 const pts=[[35.4700,51.6800],[35.4710,51.6810],[35.4720,51.6825],[35.4730,51.6840],[35.4750,51.6850]]; pts.forEach((p,i)=>db.prepare(`INSERT INTO track_points VALUES(?,?,?,?,?,?,?)`).run(uid(),mission,p[0],p[1],8,new Date(Date.parse(t1)+i*450000).toISOString(),i));
 db.prepare(`INSERT INTO mission_events VALUES(?,?,?,?,?,?,?)`).run(uid(),mission,'MISSION_STARTED',t1,35.4700,51.6800,'{}'); db.prepare(`INSERT INTO mission_events VALUES(?,?,?,?,?,?,?)`).run(uid(),mission,'MISSION_COMPLETED',t2,35.4750,51.6850,'{}');
}
seed();
const sseClients=new Set();
function broadcast(event,data){ const payload=`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`; for(const res of sseClients){try{res.write(payload)}catch{}} }
function publicUser(u){const org=db.prepare('SELECT name FROM organizations WHERE id=?').get(u.organization_id);return {id:u.id,organizationId:u.organization_id,organizationName:org?.name||'',role:u.role,position:u.position||'UNSPECIFIED',firstName:u.first_name,lastName:u.last_name,personnelCode:u.personnel_code,mobile:u.mobile,username:u.username,status:u.status}}
function positionLabel(p){return ({UNION_PRESIDENT:'رئیس اتحادیه',UNION_INSPECTOR:'بازرس اتحادیه',CHAMBER_PRESIDENT:'رئیس اتاق اصناف',CHAMBER_INSPECTOR:'بازرس اتاق اصناف',INSPECTION_RESPONSIBLE:'مسئول بازرسی'})[p]||p||'نامشخص'}
function canSupervise(u){return u.role==='MANAGER'}
function scopeOrganizationIds(u){if(u.position==='CHAMBER_PRESIDENT')return db.prepare('SELECT id FROM organizations').all().map(x=>x.id);return [u.organization_id]}
function hav(a,b,c,d){ const R=6371000,rad=x=>x*Math.PI/180; const p1=rad(a),p2=rad(c),dp=rad(c-a),dl=rad(d-b); const x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2; return 2*R*Math.asin(Math.sqrt(x)); }
function validCoordinate(lat,lng){ return Number.isFinite(Number(lat))&&Number.isFinite(Number(lng))&&Number(lat)>=-90&&Number(lat)<=90&&Number(lng)>=-180&&Number(lng)<=180; }
function validTimestamp(v){ if(v==null||v==='')return true; const t=Date.parse(v); return Number.isFinite(t); }
function normalizeOrganizationName(v){ return String(v??'').replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim().toLocaleLowerCase(); }
function findOrganizationByName(name){ const key=normalizeOrganizationName(name); if(!key)return null; return db.prepare('SELECT id,name FROM organizations').all().find(o=>normalizeOrganizationName(o.name)===key)||null; }

async function api(req,res,parts){
 const method=req.method||'GET';
 if(parts[1]==='health') return send(res,200,{ok:true,time:now(),database:'sqlite',mode:config.isProduction?'production':'development'});
 if(parts[1]==='auth' && method==='POST' && parts[2]==='login'){ const b=await json(req); if(typeof b.username!=='string'||typeof b.password!=='string'||b.username.length>120||b.password.length>256)return send(res,400,{error:'INVALID_INPUT'}); const u=db.prepare('SELECT * FROM users WHERE username=?').get(b.username); if(!u||!verifyPassword(b.password||'',u.password_hash)||u.status!=='ACTIVE') return send(res,401,{error:'INVALID_CREDENTIALS'}); const token=randomBytes(32).toString('base64url'); const sid=uid(),exp=new Date(Date.now()+config.sessionTtlDays*864e5).toISOString(); db.prepare('INSERT INTO sessions VALUES(?,?,?,?,?)').run(sid,u.id,hashToken(token),exp,now()); audit(u,'LOGIN'); const cookie=`session_token=${encodeURIComponent(token)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${config.sessionTtlDays*86400}${config.isProduction?' ; Secure':''}`.replace(' ; Secure','; Secure'); return send(res,200,{expiresAt:exp,user:publicUser(u)},{'Set-Cookie':cookie}); }
 if(parts[1]==='auth' && method==='POST' && parts[2]==='logout'){ const u=auth(req); if(u){const h=req.headers.authorization||''; const cookie=String(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('session_token=')); const tok=h.startsWith('Bearer ')?h.slice(7):(cookie?decodeURIComponent(cookie.slice('session_token='.length)):''); if(tok)db.prepare('DELETE FROM sessions WHERE token_hash=?').run(hashToken(tok)); audit(u,'LOGOUT');} return send(res,204,'',{'Set-Cookie':`session_token=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0${config.isProduction?'; Secure':''}`}); }
 if(parts[1]==='auth' && method==='GET' && parts[2]==='me'){ const u=auth(req); if(!u)return send(res,401,{error:'UNAUTHORIZED'}); return send(res,200,{user:publicUser(u)}); }
 if(parts[1]==='auth' && method==='POST' && parts[2]==='register'){ if(!config.allowRegistration)return send(res,403,{error:'REGISTRATION_DISABLED'}); const b=await json(req); if(!b.firstName||!b.lastName||!b.username||!b.password||!b.mobile||!b.organizationName)return send(res,400,{error:'REQUIRED_FIELDS'}); if(b.password.length<10)return send(res,400,{error:'WEAK_PASSWORD'}); const role=b.role==='MANAGER'?'MANAGER':'INSPECTOR'; const position=String(b.position||'').trim(); const organizationName=String(b.organizationName).replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim(); const chamber=normalizeOrganizationName(organizationName)==='اتاق اصناف'; const allowedPositions=chamber?['CHAMBER_PRESIDENT','CHAMBER_INSPECTOR','INSPECTION_RESPONSIBLE']:['UNION_PRESIDENT','UNION_INSPECTOR']; if(!allowedPositions.includes(position))return send(res,400,{error:'INVALID_ROLE'}); if((position==='CHAMBER_INSPECTOR'||position==='UNION_INSPECTOR')&&role!=='INSPECTOR')return send(res,400,{error:'INVALID_ROLE'}); if((position==='CHAMBER_PRESIDENT'||position==='INSPECTION_RESPONSIBLE'||position==='UNION_PRESIDENT')&&b.presidentCode!=='aaa123')return send(res,403,{error:'PRESIDENT_CODE_REQUIRED'}); try{ db.exec('BEGIN IMMEDIATE'); let org=findOrganizationByName(organizationName); const orgId=org?.id||('org-'+uid()); if(!org) db.prepare('INSERT INTO organizations VALUES(?,?,?,?)').run(orgId,organizationName,'Asia/Tehran',now()); const id=uid(); db.prepare(`INSERT INTO users(id,organization_id,role,position,first_name,last_name,personnel_code,mobile,username,password_hash,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,orgId,role,position,b.firstName,b.lastName,b.personnelCode||'',b.mobile,b.username,hashPassword(b.password),'ACTIVE',now(),now()); db.exec('COMMIT'); const u=db.prepare('SELECT * FROM users WHERE id=?').get(id); return send(res,201,{user:publicUser(u)});}catch(e){try{db.exec('ROLLBACK')}catch{};return send(res,409,{error:'ACCOUNT_CREATION_FAILED'});} }
 if(parts[1]==='auth' && method==='POST' && parts[2]==='forgot-password') return send(res,config.isProduction?503:202,{ok:!config.isProduction,message:config.isProduction?'Password reset provider is not configured.':'Password reset delivery is a development integration point; no reset token is returned.'});
 if(parts[1]==='sse'){ const u=auth(req); if(!u)return send(res,401,{error:'UNAUTHORIZED'}); res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive'}); res.write(`event: connected\ndata: ${JSON.stringify({userId:u.id})}\n\n`); sseClients.add(res); req.on('close',()=>sseClients.delete(res)); return; }
 const u=auth(req); if(!u)return send(res,401,{error:'UNAUTHORIZED'});
 if(parts[1]==='shops'){
   if(method==='GET'){const ids=scopeOrganizationIds(u);const marks=ids.map(()=>'?').join(',');const rows=db.prepare(`SELECT * FROM shops WHERE organization_id IN (${marks}) ORDER BY created_at DESC`).all(...ids);return send(res,200,{items:rows});}
   if(method==='POST' && u.role==='INSPECTOR'){ const b=await json(req); if(!b.name||!Number.isFinite(Number(b.latitude))||!Number.isFinite(Number(b.longitude))||!['HAS_LICENSE','NO_LICENSE'].includes(b.businessLicense))return send(res,400,{error:'INVALID_SHOP'}); const id=uid(); db.prepare(`INSERT INTO shops VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,u.organization_id,b.name,b.ownerName||'',b.mobile||'',b.nationalId||'',b.businessLicense||'',b.category||'',b.address||'',Number(b.latitude),Number(b.longitude),b.accuracy||null,b.locationTimestamp||now(),b.description||'',u.id,now(),now(),1); audit(u,'CREATE_SHOP','shop',id); broadcast('shop.created',{id,organizationId:u.organization_id}); return send(res,201,{id}); }
 }
 if(parts[1]==='employees' && method==='GET' && canSupervise(u)){let rows=[];if(u.position==='CHAMBER_PRESIDENT'){rows=db.prepare(`SELECT u.id,u.first_name,u.last_name,u.personnel_code,u.mobile,u.username,u.status,u.role,u.position,o.name organization_name FROM users u JOIN organizations o ON o.id=u.organization_id WHERE u.position IN ('UNION_PRESIDENT','UNION_INSPECTOR','CHAMBER_INSPECTOR') ORDER BY o.name,u.last_name,u.first_name`).all()}else if(u.position==='INSPECTION_RESPONSIBLE'){rows=db.prepare(`SELECT u.id,u.first_name,u.last_name,u.personnel_code,u.mobile,u.username,u.status,u.role,u.position,o.name organization_name FROM users u JOIN organizations o ON o.id=u.organization_id WHERE u.organization_id=? AND u.position='CHAMBER_INSPECTOR' ORDER BY u.last_name,u.first_name`).all(u.organization_id)}else{rows=db.prepare(`SELECT u.id,u.first_name,u.last_name,u.personnel_code,u.mobile,u.username,u.status,u.role,u.position,o.name organization_name FROM users u JOIN organizations o ON o.id=u.organization_id WHERE u.organization_id=? AND u.position='UNION_INSPECTOR' ORDER BY u.last_name,u.first_name`).all(u.organization_id)}return send(res,200,{items:rows.map(x=>({id:x.id,firstName:x.first_name,lastName:x.last_name,personnelCode:x.personnel_code,mobile:x.mobile,username:x.username,status:x.status,role:x.role,position:x.position,roleLabel:positionLabel(x.position),organizationName:x.organization_name}))})}
 if(parts[1]==='missions'){
   if(method==='GET'){const ids=scopeOrganizationIds(u);const marks=ids.map(()=>'?').join(',');let rows=db.prepare(`SELECT * FROM missions WHERE organization_id IN (${marks}) ORDER BY created_at DESC`).all(...ids);if(u.role==='INSPECTOR')rows=rows.filter(x=>x.inspector_id===u.id);return send(res,200,{items:rows});}
   if(method==='POST' && !parts[2] && u.role==='INSPECTOR'){ const b=await json(req); if(!validCoordinate(b.latitude,b.longitude)||!validTimestamp(b.startTime))return send(res,400,{error:'INVALID_LOCATION'}); const existing=db.prepare(`SELECT id FROM missions WHERE inspector_id=? AND status='ACTIVE' LIMIT 1`).get(u.id); if(existing)return send(res,409,{error:'ACTIVE_MISSION_EXISTS',missionId:existing.id}); const id=uid(); const start=new Date(b.startTime||now()).toISOString(); try{ db.prepare(`INSERT INTO missions VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,u.organization_id,u.id,'ACTIVE',start,null,Number(b.latitude),Number(b.longitude),null,null,0,now(),now(),1); }catch(e){ if(e?.code==='SQLITE_CONSTRAINT_UNIQUE') { const active=db.prepare(`SELECT id FROM missions WHERE inspector_id=? AND status='ACTIVE' LIMIT 1`).get(u.id); if(active)return send(res,409,{error:'ACTIVE_MISSION_EXISTS',missionId:active.id}); } throw e; } db.prepare(`INSERT INTO mission_events VALUES(?,?,?,?,?,?,?)`).run(uid(),id,'MISSION_STARTED',start,Number(b.latitude),Number(b.longitude),'{}'); audit(u,'START_MISSION','mission',id); broadcast('mission.started',{missionId:id,inspectorId:u.id,latitude:Number(b.latitude),longitude:Number(b.longitude)}); return send(res,201,{id}); }
   if(method==='POST' && parts[2] && parts[3]==='end' && u.role==='INSPECTOR'){ const id=parts[2]; const m=db.prepare('SELECT * FROM missions WHERE id=? AND organization_id=? AND inspector_id=?').get(id,u.organization_id,u.id); if(!m||m.status!=='ACTIVE')return send(res,404,{error:'MISSION_NOT_ACTIVE'}); const b=await json(req); if(!validCoordinate(b.latitude,b.longitude)||!validTimestamp(b.endTime))return send(res,400,{error:'INVALID_LOCATION'}); const pts=db.prepare('SELECT * FROM track_points WHERE mission_id=? ORDER BY seq').all(id); let dist=0; for(let i=1;i<pts.length;i++)dist+=hav(pts[i-1].latitude,pts[i-1].longitude,pts[i].latitude,pts[i].longitude); const end=new Date(b.endTime||now()).toISOString(); db.prepare('UPDATE missions SET status=?,end_time=?,end_latitude=?,end_longitude=?,distance=?,updated_at=?,version=version+1 WHERE id=?').run('COMPLETED',end,Number(b.latitude),Number(b.longitude),dist,now(),id); db.prepare(`INSERT INTO mission_events VALUES(?,?,?,?,?,?,?)`).run(uid(),id,'MISSION_COMPLETED',end,Number(b.latitude),Number(b.longitude),'{}'); audit(u,'END_MISSION','mission',id,{distance:dist}); broadcast('mission.completed',{missionId:id}); return send(res,200,{distance:dist}); }
   if(method==='POST' && parts[2] && parts[3]==='track' && u.role==='INSPECTOR'){ const id=parts[2]; const m=db.prepare('SELECT * FROM missions WHERE id=? AND organization_id=? AND inspector_id=? AND status=\'ACTIVE\'').get(id,u.organization_id,u.id); if(!m)return send(res,404,{error:'MISSION_NOT_ACTIVE'}); const b=await json(req); if(!validCoordinate(b.latitude,b.longitude)||!validTimestamp(b.timestamp))return send(res,400,{error:'INVALID_LOCATION'}); const last=db.prepare('SELECT * FROM track_points WHERE mission_id=? ORDER BY seq DESC LIMIT 1').get(id); const seq=last?last.seq+1:0; if(last && hav(last.latitude,last.longitude,Number(b.latitude),Number(b.longitude))<10)return send(res,200,{accepted:false,reason:'DISTANCE_THRESHOLD'}); const tp=uid(); db.prepare(`INSERT INTO track_points VALUES(?,?,?,?,?,?,?)`).run(tp,id,Number(b.latitude),Number(b.longitude),Number(b.accuracy||0),new Date(b.timestamp||now()).toISOString(),seq); broadcast('tracking.point',{missionId:id,inspectorId:u.id,latitude:Number(b.latitude),longitude:Number(b.longitude),timestamp:b.timestamp||now()}); return send(res,201,{accepted:true,id:tp,seq}); }
 }
 if(parts[1]==='inspections' && method==='POST' && u.role==='INSPECTOR'){ const b=await json(req); if(typeof b.shopId!=='string'||typeof b.missionId!=='string'||typeof b.result!=='string'||b.result.length>10000)return send(res,400,{error:'INVALID_INPUT'}); const shop=db.prepare('SELECT id FROM shops WHERE id=? AND organization_id=?').get(b.shopId,u.organization_id); const mission=db.prepare('SELECT id FROM missions WHERE id=? AND inspector_id=? AND organization_id=?').get(b.missionId,u.id,u.organization_id); if(!shop||!mission)return send(res,400,{error:'INVALID_RELATION'}); const id=uid(),ts=now(); db.prepare(`INSERT INTO inspections VALUES(?,?,?,?,?,?,?,?,?,?)`).run(id,u.organization_id,b.shopId,u.id,b.missionId,ts,b.result,b.notes||'',ts,ts); db.prepare(`INSERT INTO mission_events VALUES(?,?,?,?,?,?,?)`).run(uid(),b.missionId,'INSPECTION_CREATED',ts,b.latitude||null,b.longitude||null,JSON.stringify({shopId:b.shopId,inspectionId:id})); audit(u,'CREATE_INSPECTION','inspection',id); return send(res,201,{id}); }
 if(parts[1]==='warnings' && method==='POST' && u.role==='INSPECTOR'){ const b=await json(req); if(typeof b.shopId!=='string'||typeof b.missionId!=='string'||typeof b.reason!=='string'||!b.reason.trim()||b.reason.length>5000)return send(res,400,{error:'INVALID_INPUT'}); const id=uid(),ts=now(),num='WR-'+new Date().getFullYear()+'-'+Math.random().toString(36).slice(2,8).toUpperCase(); db.prepare(`INSERT INTO warnings VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,num,u.organization_id,b.shopId,u.id,b.missionId,ts,b.reason,b.description||'','OPEN',ts,ts); db.prepare(`INSERT INTO mission_events VALUES(?,?,?,?,?,?,?)`).run(uid(),b.missionId,'WARNING_CREATED',ts,b.latitude||null,b.longitude||null,JSON.stringify({shopId:b.shopId,warningId:id})); audit(u,'CREATE_WARNING','warning',id); return send(res,201,{id,warningNumber:num}); }
 if(parts[1]==='inspections' && method==='GET'){const ids=scopeOrganizationIds(u);const marks=ids.map(()=>'?').join(',');const rows=db.prepare(`SELECT i.*,s.name shop_name,u.first_name inspector_first_name,u.last_name inspector_last_name FROM inspections i JOIN shops s ON s.id=i.shop_id JOIN users u ON u.id=i.inspector_id WHERE i.organization_id IN (${marks}) ORDER BY i.timestamp DESC`).all(...ids);if(u.role==='INSPECTOR')return send(res,200,{items:rows.filter(x=>x.inspector_id===u.id)});if(!canSupervise(u))return send(res,403,{error:'FORBIDDEN'});return send(res,200,{items:rows})}
 if(parts[1]==='warnings' && method==='GET'){const ids=scopeOrganizationIds(u);const marks=ids.map(()=>'?').join(',');const rows=db.prepare(`SELECT w.*,s.name shop_name,u.first_name inspector_first_name,u.last_name inspector_last_name FROM warnings w JOIN shops s ON s.id=w.shop_id JOIN users u ON u.id=w.inspector_id WHERE w.organization_id IN (${marks}) ORDER BY w.date DESC`).all(...ids);if(u.role==='INSPECTOR')return send(res,200,{items:rows.filter(x=>x.inspector_id===u.id)});if(!canSupervise(u))return send(res,403,{error:'FORBIDDEN'});return send(res,200,{items:rows})}
 if(parts[1]==='monitoring' && method==='GET' && canSupervise(u)){const ids=scopeOrganizationIds(u);const marks=ids.map(()=>'?').join(',');let filter='';if(u.position==='INSPECTION_RESPONSIBLE')filter=" AND u.position='CHAMBER_INSPECTOR'";else if(u.position==='UNION_PRESIDENT')filter=" AND u.position='UNION_INSPECTOR'";else if(u.position==='CHAMBER_PRESIDENT')filter=" AND u.position IN ('UNION_INSPECTOR','CHAMBER_INSPECTOR')";const rows=db.prepare(`SELECT m.*,u.first_name,u.last_name,u.position,o.name organization_name FROM missions m JOIN users u ON u.id=m.inspector_id JOIN organizations o ON o.id=u.organization_id WHERE m.organization_id IN (${marks}) AND m.status='ACTIVE'${filter}`).all(...ids);const shops=db.prepare(`SELECT * FROM shops WHERE organization_id IN (${marks}) ORDER BY created_at DESC`).all(...ids);return send(res,200,{items:rows.map(x=>({...x,roleLabel:positionLabel(x.position)})),shops})}
 if(parts[1]==='route' && method==='GET' && parts[2]){const ids=scopeOrganizationIds(u);const marks=ids.map(()=>'?').join(',');const m=db.prepare(`SELECT * FROM missions WHERE id=? AND organization_id IN (${marks})`).get(parts[2],...ids);if(!m||(u.role==='INSPECTOR'&&m.inspector_id!==u.id))return send(res,404,{error:'NOT_FOUND'}); const points=db.prepare('SELECT latitude,longitude,accuracy,timestamp,seq FROM track_points WHERE mission_id=? ORDER BY seq').all(parts[2]); const events=db.prepare('SELECT * FROM mission_events WHERE mission_id=? ORDER BY timestamp').all(parts[2]); return send(res,200,{mission:m,points,events}); }
 if(parts[1]==='reports' && method==='GET' && canSupervise(u)){const ids=scopeOrganizationIds(u);const marks=ids.map(()=>'?').join(',');const shops=db.prepare(`SELECT * FROM shops WHERE organization_id IN (${marks})`).all(...ids);const inspections=db.prepare(`SELECT * FROM inspections WHERE organization_id IN (${marks})`).all(...ids);const warnings=db.prepare(`SELECT * FROM warnings WHERE organization_id IN (${marks})`).all(...ids);const missions=db.prepare(`SELECT * FROM missions WHERE organization_id IN (${marks})`).all(...ids);return send(res,200,{shops,inspections,warnings,missions});}
 return send(res,404,{error:'NOT_FOUND'});
}

const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'};
const server=createServer(async(req,res)=>{ try{ if(new URL(req.url||'/',`http://${req.headers.host||'localhost'}`).pathname==='/health') return send(res,200,{ok:true,time:now(),database:'sqlite',mode:config.isProduction?'production':'development'}); if(req.url?.startsWith('/api/')) { const origin=req.headers.origin; const allowed=!origin || (!!config.appOrigin && origin===config.appOrigin); if(!allowed)return send(res,403,{error:'CORS_ORIGIN_DENIED'}); if(origin)res.setHeader('Access-Control-Allow-Origin',origin); res.setHeader('Vary','Origin'); res.setHeader('Access-Control-Allow-Headers','Authorization, Content-Type'); res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS'); if(req.method==='OPTIONS')return send(res,204,''); if(!rateLimit(req,res,req.url.includes('/auth/') ? config.authRateLimitMax : config.rateLimitMax)) return; return await api(req,res,pathParts(req.url)); } let p=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`).pathname; if(p==='/')p='/index.html'; const file=join(WEB,p); if(resolve(file)!==WEB && (relative(WEB,resolve(file)).startsWith('..'+sep)||relative(WEB,resolve(file))==='..'||resolve(file)===resolve(WEB,'..')))return send(res,403,'Forbidden'); try{await stat(file); const body=await readFile(file); res.writeHead(200,{'Content-Type':mime[extname(file)]||'application/octet-stream','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'strict-origin-when-cross-origin',...(config.isProduction?{'Strict-Transport-Security':'max-age=31536000; includeSubDomains'}:{})});res.end(body);}catch{const body=await readFile(join(WEB,'index.html'));res.writeHead(200,{'Content-Type':mime['.html'],'X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY'});res.end(body);} }catch(e){console.error(e?.stack||e);send(res,e?.statusCode===413?413:400,{error:e?.statusCode===413?'PAYLOAD_TOO_LARGE':'INVALID_REQUEST'});} });
server.listen(PORT,config.host,()=>console.log(`Pakdasht Inspection listening on ${config.host}:${PORT}`));
